### ISSUE TITLE
How to change the port from localhost:8000 to localhost:8080 ? which file has the URL information ?

### ISSUE THREAD

**Issue by Sathish1891** [matterport/showcase-sdk-examples#45]

**Comment by databird** [comment]
When you start the webserver, specify the port at the end of the command line :
`python3.6 matterport-dl.py [tourID] localhost 8080`

**Comment by dmtaub** [comment]
for development, we are using `webpack-dev-server` you can pass a `--port 8080` in order to run on that port, but if you're running from the toplevel directory, you will need to use `--` TWICE to tell the scripts to pass the arguments along, rather than trying to interpret them. 

So for example `yarn inspector -- -- --port 8080` should run the inspector on port 8080.
Yarn calls lerna, passing the argument `-- --port...`. Lerna calls the npm script for webpack, with `--port...` .

If you have additional questions, please visit https://matterport.com/platform/developers for documentation or to contact the SDK support team
